version: '3'
services: 
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /home/node/node_modules
            - ./server:/home/node
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /home/node/node_modules
            - ./client:/home/node
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /home/node/node_modules
            - ./worker:/home/node
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379